#! /usr/bin/env python

import sys
import os
import os.path
import traceback
import threading
import time

from cleo import Cleo

os.environ['CLEO_HOME'] = os.path.dirname(os.path.realpath(sys.argv[0]))
cm = Cleo()
cm.start()

try:
	while len(threading.enumerate()) > 1:
		#print threading.enumerate()
		time.sleep(0.5)
except:
	info = sys.exc_info()
	traceback.print_tb(info[2])
	print info[1]

cm.stop()

print('Goodbye')

