#! /usr/bin/env python

# Copyright 2009-2011 Klas Lindberg <klas.lindberg@gmail.com>

# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 3, as published
# by the Free Software Foundation.

import sys
import os
import os.path
import traceback
import threading
import time

from cleo import Cleo

path = os.path.expanduser('~/.dwite')
os.environ['DWITE_CFG_DIR'] = path
if not os.path.isdir(path):
	raise Exception('No configuration directory "%s"' % path)

try:
	cm = Cleo()
	cm.start()
	while True:
		if cm.isAlive():
			time.sleep(0.5)
		else:
			cm = Cleo()
			cm.start()
except:
	info = sys.exc_info()
	traceback.print_tb(info[2])
	print info[1]

cm.stop()

print('Goodbye')

