#! /usr/bin/env python

# Copyright 2011 Klas Lindberg <klas.lindberg@gmail.com>

# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 3, as published
# by the Free Software Foundation.

import sys

import cli

if __name__ == '__main__':
	cmd = unicode(sys.argv[1])
	url = unicode(sys.argv[2])
	seek = int(sys.argv[3])
	cli.run(cmd, url, seek)

