#! /usr/bin/env python

# Copyright 2009-2011 Klas Lindberg <klas.lindberg@gmail.com>

# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 3, as published
# by the Free Software Foundation.

import sys
import os
import os.path
import traceback
import threading
import time

from conman import Conman

path = os.path.expanduser('~/.dwite')
os.environ['DWITE_CFG_DIR'] = path
if not os.path.isdir(path):
	raise Exception('No configuration directory "%s"' % path)

try:
	cm = Conman()
	cm.start()
	while True:
		if cm.is_alive():
			time.sleep(0.5)
		else:
			break
except KeyboardInterrupt:
	pass
except:
	traceback.print_exc()

cm.stop(hard=True)

while threading.active_count() > 1:
	print [t.name for t in threading.enumerate()]
	time.sleep(1)

print('Goodbye')

