#! /usr/bin/env python

# Copyright 2009-2011 Klas Lindberg <klas.lindberg@gmail.com>

# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 3, as published
# by the Free Software Foundation.

import sys
import os
import os.path
import traceback
import threading
import time
import getopt

if sys.version_info < (2,6):
	print("Python 2.6 or higher is required")
	sys.exit(1)
if sys.version_info >= (3,0):
	print("Python 3 not supported yet")
	sys.exit(1)

from conman import Conman, Scan

def syntax():
	print('Syntax: conman [--scan]')
	sys.exit(1)

if __name__ == '__main__':
	path = os.path.expanduser('~/.dwite')
	os.environ['DWITE_CFG_DIR'] = path
	if not os.path.isdir(path):
		raise Exception('No configuration directory "%s"' % path)
	
	try:
		(opts, args) = getopt.gnu_getopt(sys.argv, '', ['scan'])
	except:
		syntax()

	scan = False
	for (opt, arg) in opts:
		if opt == '--scan':
			scan = True

	try:
		cm = Conman()
		if scan:
			cm.queue.put(Scan())
		cm.start()
		while True:
			if cm.is_alive():
				time.sleep(0.5)
			else:
				break
	except KeyboardInterrupt:
		pass
	except:
		traceback.print_exc()

	cm.stop(hard=True)

	while threading.active_count() > 1:
		print [t.name for t in threading.enumerate()]
		time.sleep(1)

	print('Goodbye')

