#! /usr/bin/env python

# Copyright 2009-2011 Klas Lindberg <klas.lindberg@gmail.com>

# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 3, as published
# by the Free Software Foundation.

import sys
import os

if sys.version_info < (2,6):
	print("Python 2.6 or higher is required")
	sys.exit(1)
if sys.version_info >= (3,0):
	print("Python 3 not supported yet")
	sys.exit(1)

import dwite

os.environ['DWITE_HOME']    = os.path.dirname(os.path.realpath(sys.argv[0]))
os.environ['DWITE_CFG_DIR'] = os.path.expanduser('~/.dwite')
dwite.main()

