#! /usr/bin/env python

# Copyright 2009-2011 Klas Lindberg <klas.lindberg@gmail.com>

# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 3, as published
# by the Free Software Foundation.

import sys
import os
import os.path
import dwite

os.environ['DWITE_HOME'] = os.path.dirname(os.path.realpath(sys.argv[0]))
dwite.main()
print('Goodbye')

