#! /usr/bin/env python

# Copyright 2009-2011 Klas Lindberg <klas.lindberg@gmail.com>

# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 3, as published
# by the Free Software Foundation.

import sys
import os
import time
import traceback

if sys.version_info < (2,6):
	print("Python 2.6 or higher is required")
	sys.exit(1)
if sys.version_info >= (3,0):
	print("Python 3 not supported yet")
	sys.exit(1)

from multiprocessing import Process

import dwite
import conman

if __name__ == '__main__':
	os.environ['DWITE_HOME']    = os.path.dirname(os.path.realpath(sys.argv[0]))
	os.environ['DWITE_CFG_DIR'] = os.path.expanduser('~/.dwite')

	try:
		dm = Process(target=dwite.main)
		cm = Process(target=conman.main, args=(sys.argv,))
		dm.start()
		cm.start()

		while dm.is_alive() or cm.is_alive():
			time.sleep(1)
	except KeyboardInterrupt:
		pass
	except:
		traceback.print_exc()
