"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['launcher.py']
DATA_FILES = ['lib', 'fonts']
OPTIONS = {
	'argv_emulation': True,
	'plist': {
		'CFBundleName': 'Dwite',
		'CFBundleDisplayName': 'Dwite',
		'CFBundleExecutable': 'launcher',
		'CFBundleIdentifier': 'nu.klax.dwite'
	}
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
